"""Add github_repo field to projects table

Revision ID: e4cb499bf976
Revises: 047bcf2fb78a
Create Date: 2026-07-17 10:22:30.196495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4cb499bf976'
down_revision: Union[str, Sequence[str], None] = '047bcf2fb78a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('github_repo', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'github_repo')
    # ### end Alembic commands ###
